# hello_world_golang/function.yaml
output_dataset: hello_world_golang
# This will trigger the function to execute on every new Ethereum block.
triggers:
  - path: eth
# This selects the runtime that will execute your code.
runtime: go1.x
# For Golang, handler is [function_file].go
# The below will invoke the main method in a file `spice_function.go`.
handler: spice_function.go
